### ISSUE TITLE
emacs-twiki-mode gets confused on long file names in bullet list when saving

### ISSUE THREAD

**Issue by martinkarlweber** [christopherjwhite/emacs-twiki-mode#4]
I'm a big fan of emacs-twiki-mode but it has the annoying feature that when entering certain strings, e.g. long file names, in a bullet list the mode gets confused when saving the file. E.g. after entering the string "/path/to/file/with/long/string/that/expands/over/more/than/a/single/line/then/emacs/twiki/mode/gets/confused ", emacs ends up in an endless loop and inserts white space before the string. Upon pressing ^G, the process stops but then zillions of white space has been added.

Take the next line (single line) as a TWiki document and have fun.

<pre>
   * Test entry /path/to/file/with/long/string/that/expands/over/more/than/a/single/line/then/emacs/twiki/mode/gets/confused
</pre>

**Comment by christopherjwhite** [comment]
Yep -- I ran into this issue myself and spent some time working on it a few months back.  Can you confirm that you are using the latest version of the code?   I tested your single line and it works for me without a problem.  It moves the long filename to the second line, indented appropriately.

If you are running the latest and still seeing the problem, can you provide more details about your environment -- emacs-version, operating system, any special packages you like to run, anything you think might be relevant.

**Comment by martinkarlweber** [comment]
I downloaded the last version of twiki.el and auto-installed it in emacs 
before submitting the bug report. I must have forgotten to restart emacs, 
which I did just now and indeed the problem is gone.

Thanks!

Am Freitag, 22. März 2013, 06:57:55 schrieb Christopher J. White:

**Comment by christopherjwhite** [comment]
Excellent - that's the kind of bug report I like to see -- the one that's already fixed!  ;-)
